apiVersion: v1
kind: Service
metadata:
  name: matchmaking-service
  namespace: tfi-prod
spec:
  type: ClusterIP
  selector:
    app: matchmaking-service
  ports:
    - port: 4205
      targetPort: 4205
