apiVersion: v1
kind: Service
metadata:
  name: ai-assistant-service
  namespace: tfi-prod
spec:
  type: ClusterIP
  selector:
    app: ai-assistant-service
  ports:
    - port: 4401
      targetPort: 4401

