apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: tfi-prod
type: Opaque
stringData:
  DATABASE_URL: "postgres://tfi_prod:CHANGE_ME_STRONG_PASSWORD@postgres:5432/tfi_production"
  JWT_SECRET: "CHANGE_ME_JWT_SECRET_AT_LEAST_32_CHARS"
  RABBITMQ_PASS: "CHANGE_ME_RABBITMQ_PASSWORD"
  POSTGRES_PASSWORD: "CHANGE_ME_STRONG_PASSWORD"
